apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linear-inspired-ingress
  namespace: linear-demo
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: web
      port:
        number: 80
